version: '3.8'

services:
    database:
        image: mariadb
        container_name: loki-database
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_RANDOM_ROOT_PASSWORD: yes
        ports:
            - '3306:3306'
        networks:
            - loki-network
        volumes:
            - ./loki/database:/var/lib/mysql
            - ./database/scripts:/docker-entrypoint-initdb.d

    backend:
        build:
            context: .
            dockerfile: ./docker/Dockerfile-backend
        container_name: loki-backend
        restart: unless-stopped
        ports:
            - "3000:3000"
        environment:
            MEDIA_PATH: /media
            TRANSCODE_PATH: /loki/transcode
            CACHE_DIR: /loki/cache
            METADATA_PATH: /loki/metadata
            FFMPEG_HWACCEL: ${FFMPEG_HWACCEL:-auto}
            NVIDIA_VISIBLE_DEVICES: all
            NVIDIA_DRIVER_CAPABILITIES: all
        env_file:
            - .env
        networks:
            - loki-network
        healthcheck:
            test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health" ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        volumes:
            - ./loki/transcode:/loki/transcode:rw
            - ./loki/cache:/loki/cache:rw
            - ./loki/metadata:/loki/metadata:rw
            - ${MEDIA_PATH}:/media:rw
            # Hardware acceleration (intel/amd gpus)
            - /dev/dri:/dev/dri
        # GPU Support
        devices:
            - /dev/dri:/dev/dri
        # NVIDIA GPU Support
        deploy:
            resources:
                reservations:
                    devices:
                        -   driver: nvidia
                            count: all
                            capabilities: [ gpu, video, compute, utility ]

    frontend:
        build:
            context: .
            dockerfile: ./docker/Dockerfile-frontend
            args:
                - VITE_API_URL=/api
        container_name: loki-frontend
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        networks:
            - loki-network
        volumes:
            - ./docker/ssl:/etc/nginx/ssl:ro  # Optional: for SSL-Certificates

networks:
    loki-network:
        driver: bridge