version: '3.8'

services:
    database:
        image: mariadb
        container_name: loki-database
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_RANDOM_ROOT_PASSWORD: yes
        ports:
            - '3306:3306'
        networks:
            - loki-network
        volumes:
            - ./data/database:/var/lib/mysql
            - ./database/scripts:/docker-entrypoint-initdb.d

    backend:
        build:
            context: .
            dockerfile: ./docker/Dockerfile-backend
        container_name: loki-backend
        restart: unless-stopped
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
        env_file:
            - .env
        networks:
            - loki-network
        healthcheck:
            test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health" ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

    frontend:
        build:
            context: .
            dockerfile: ./docker/Dockerfile-frontend
            args:
                - VITE_API_URL=/api
        container_name: loki-frontend
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        networks:
            - loki-network
        volumes:
            - ./docker/ssl:/etc/nginx/ssl:ro  # Optional: for SSL-Certificates

networks:
    loki-network:
        driver: bridge